### PR TITLE
Demolish

### PR DESCRIPTION
**Pull request by Denpeer**
The agent in the state as it was during the Demo with bachelli.

This pull request updates our agent to the one used in the demo, because mainly worked in this branch the pull request is very big.

User story:
As a virtual human I want to dynamically demolish and build to fulfill my goals.

### CODE REVIEW

**Comment by MaxGroenenboom** [comment]
It would have been better if this had been splitted in separate PR's, but nevertheless I approve.

**Comment by Denpeer** [comment]
@MaxGroenenboom We agreed to do it this way for the demo.

**Comment by klikooo** [comment]
I approve

**Comment by MaxGroenenboom** [comment]
Looks good, and it runs well. I approve.

**Comment by MarcianoJ** [comment]
I approve, too

**Pull request merged**
