### PR TITLE
Municipality interaction improved

### PR DESCRIPTION
**Pull request by Denpeer**
User Story:
As a virtual human, I want to interact with other stakeholders by doing more than just building student housing

### CODE REVIEW

**Comment by MaxGroenenboom** [comment]
Can you remove the old environment jar? It still is in there, while it hasn't been used for weeks.

**Comment by Denpeer** [comment]
@MaxGroenenboom Done

**Comment by MaxGroenenboom** [comment]
Since it builds and I have seen it working during the demo, I approve.

**Comment by klikooo** [comment]
# I APPROVE

**Pull request merged**
